name: Upload Gatsby Artifacts to S3 (buildless, diff-only)

on:
  push:
    branches: [main]
    paths:
      - "public/**"

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (shallow)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy (diff-only sync & smart invalidation)
        run: bash ./deploy.sh
